language: python
python:
- '2.7'
- '3.5'
cache:
  pip: true
  directories:
  - ".genome/"
addons:
  apt:
    packages:
    - build-essential
    - curl
    - ncbi-blast+
    - muscle
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran
    - tabix
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda update --yes conda
- conda config --add channels bioconda
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION pytest pytest-cov numpy scipy
  cython biopython bwa samtools bcftools vcftools blast primer3=2.3.7
- pip install coveralls
- pip install pytest-cov
- python setup.py develop
script:
- py.test --verbose --cov-report=term --cov=vcfkit tests
after_success:
- coveralls
- conda remove --yes curl
